# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 09:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi_prefix', models.CharField(max_length=255)),
                ('doi_suffix', models.CharField(max_length=255)),
                ('crossref', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('zenodo_deposit', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('has_been_uploaded', models.BooleanField(default=False)),
                ('free_fulltext_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doi.Article')),
            ],
        ),
    ]
