# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doi', '0003_auto_20170601_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='zenodo_deposit',
            new_name='zenodo',
        ),
    ]
