# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doi', '0004_auto_20170601_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illegal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.FileField(upload_to='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doi.Article')),
            ],
        ),
    ]
